### ISSUE TITLE
Cropper view shows stretched image

### ISSUE THREAD

**Issue by f0enix** [ZhongUncle/SwiftUI_ImageCropper#3]
The cropper image view is stretching the image. It should display it in aspect fit mode to prevent any stretching and display images in their proper aspect ratio irrespective of their size. In the example below, i passed a landscape image to the cropper and it stretched it  in the cropper view (can be seen clearly with the long stretched phone)
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-08 at 12 39 22](https://user-images.githubusercontent.com/72214428/200516335-28caa922-9fb3-4b4c-9410-11b536119ece.png)

**Comment by ZhongUncle** [comment]
Recently I'm busy, I'm sorry reply you now.
Thanks for report this bug. Because I didn't test much in iPad, so it needs some time to fix this bug or other bugs in iPad.

**Comment by ZhongUncle** [comment]
I found the cause of this bug. It's also from Apple update. 
Apple deprecated `NavigationView` from iOS 16. And now if using `NavigationView`, it shows the sidebar like you see in iPadOS. 
I will fix this and corresponding bugs. Thanks for your using.
