### ISSUE TITLE
Cropper vertices can go beyond the image

### ISSUE THREAD

**Issue by f0enix** [ZhongUncle/SwiftUI_ImageCropper#7]
if i click and drag the top right corner vertex multiple times, i am able to make the cropper view go outside the image. The cropper vertices should be limited to the four corners of the image
![Simulator Screen Shot - iPhone 13 mini - 2023-01-04 at 10 51 27](https://user-images.githubusercontent.com/72214428/210499968-4bb7a470-473f-4990-9004-9c45a1a4527c.png)

**Comment by ZhongUncle** [comment]
Do you have this error now?
