### ISSUE TITLE
 报错了

### ISSUE THREAD

**Issue by johs-aly** [ZhongUncle/SwiftUI_ImageCropper#8]
/Users/dhzy/Desktop/image/image/CropperView.swift:62:25: The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
/Users/dhzy/Desktop/image/image/ImageCropperView.swift:218:38: Cannot find 'CropperViewModel' in scope  报错了

**Comment by ZhongUncle** [comment]
请问你是自己修改过代码么？因为我没有使用Storyboard，所以不会有ViewModel这些代码结构。此外，你可以提供更多的一些信息么？比如系统、Xcode版本，平台类型（Apple Silicon还是Intel），以及你是使用Xcode还是命令行构建项目的。因为我并没有复现你的错误，无法知道为什么出现这个问题。

不过也感谢你提醒我，之前有次版本提交了错误的设置，这次我自己构建才发现，不过应该不是你这个问题的错误原因。
